# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HASS Proton Calendar
version: "1.0.0"
slug: example
description: Home Assistant Proton Calendar Add-on
url: "https://github.com/ChaseAlberti/hass-proton-calendar/edit/main/hass-proton-calendar"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world!"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
